apiVersion: v1
kind: Service
metadata:
  name: polyshop-product-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: polyshop-product-mongodb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: polyshop-order-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: polyshop-order-postgres
  type: ClusterIP
